version: '2.3'
services:
  dhcpd:
    build:
      context: dhcpd
    network_mode: host
    command: ["vboxnet0"]
    volumes:
    - ./dhcpd/dhcpd.conf:/etc/dhcpd.conf:ro
  tftpd:
    build:
      context: tftpd
    volumes:
    - ./media:/data/media:ro
    - ./static:/data/static:ro
    network_mode: host
    command: ["-a", "192.168.56.1"]

  nginx:
    build:
      context: nginx
    volumes:
    - ./media:/data/media:ro
    - ./static:/data/static:ro
    cap_add:
    - NET_BIND_SERVICE
    ports:
    - "192.168.56.1:80:80"