version: '2.3'
services:
  dhcpd:
    build:
      context: dhcpd
    network_mode: host
    command: ["vboxnet0"]
    volumes:
    - ./dhcpd/dhcpd.conf:/etc/dhcpd.conf:ro

#  tftpd:
#    build:
#      context: tftpd
#    volumes:
#    - ./media:/data/media:ro
#    - ./static:/data/static:ro
#    network_mode: host
#    command: ["-a", "192.168.56.1"]

  nfsd:
    build:
      context: nfsd
    privileged: true
    volumes:
    - ./media:/data/media:ro
    - ./static:/data/static:ro
    ports:
    - "192.168.56.1:111:111/udp"
    - "192.168.56.1:2049:2049/tcp"
    - "192.168.56.1:2049:2049/udp"

  nginx:
    build:
      context: nginx
    volumes:
    - ./media:/data/media:ro
    - ./static:/data/static:ro
    cap_add:
    - NET_BIND_SERVICE
    ports:
    - "192.168.56.1:80:80"